name: Deploy to Infomaniak

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: mu5vg.ftp.infomaniak.com
        username: mu5vg_joathan
        password: ${{ secrets.FTP_PASSWORD }}
	local-dir: ./  # Dossier local à déployer, doit se terminer par /
        server-dir: /sites/deploy.cosourcing.fr
